    password:
    
    debconf:
    - question: "slapd/move_old_database"
      value: true 
      vtype: select
    - question: "shared/organization"
      value: "Unibo" 
      vtype: string
    - question: "slapd/no_configuration" 
      value: false
      vtype: boolean
    - question: "slapd/domain"
      value: "labammsis" 
      vtype: string
    - question: "slapd/purge_database"
      value: true
      vtype: boolean
    - question: "slapd/move_old_database"
      value: true 
      vtype: boolean
    - question: "slapd/slapd/invalid_config"
      value: false
      vtype: boolean
    - question: "slapd/password1"
      value: "gennaio.marzo"
      vtype: password
    - question: "slapd/password2"
      value: "gennaio.marzo"
      vtype: password
    